[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'jsx'

# [[plugins]]
# repo = 'zchee/deoplete-go'
# on_ft = 'go'
#   [plugins.build]
#   mac = 'make'

# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'
