[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'jsx'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = 'tsx'

[[plugins]]
repo = 'mhartington/deoplete-typescript'
on_ft = ['ts', 'tsx', 'typescript.tsx', 'typescrpt']

[[plugins]]
repo = 'steelsojka/deoplete-flow'
on_ft = ['javascript', 'javascript.jsx']

