(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.jsp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))

(setq web-mode-style-padding 2)
(setq web-mode-script-padding 2)
;; (define-key web-mode-map (kbd "C-;") 'my-helm)
;; (define-key web-mode-map (kbd "M-;") 'nxml-mode-comment-or-uncomment-region)
(setq web-mode-comment-style 2)

;; 全部2にする
(defun web-mode-hook ()
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-indent-style  2)
  (setq web-mode-html-offset   2)
  (setq web-mode-css-offset    2)
  (setq web-mode-script-offset 2)
  (setq web-mode-php-offset    2)
  (setq web-mode-java-offset   2)
  (setq web-mode-asp-offset    2))
(add-hook 'web-mode-hook 'web-mode-hook)
